apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo-ns
type: Opaque
data:
  # Values are base64 encoded for "root" and "example"
  mongo-root-username: cm9vdA==
  mongo-root-password: ZXhhbXBsZQ==
