apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: muchtodo-ns
data:
  .env: |
    MONGO_URI=mongodb://root:example@mongodb:27017/much_todo_db?authSource=admin
    REDIS_ADDR=redis:6379
    DB_NAME=much_todo_db
    PORT=3000
    ENABLE_CACHE=true
